from node:latest

WORKDIR /usr/src/app

COPY . .
RUN npm install create-react-app -g && \
npm install --save node-sass-chokidar &&\
npm install react-router
CMD ["time","yarn", "install"]
CMD ["node", "index.js"]
