name: ci
on: [push] #sempre que for dar um push
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #actions é o usuario e o checkout o repositorio
      - uses: actions/setup-node@v2
        with:
          go-version: 1.15
      - run: npm test
      - run: npm start
